from bigcrittercolor.createBigcrittercolorDataFolder import createBigcrittercolorDataFolder
from bigcrittercolor.downloadiNatImagesAndData import downloadiNatImagesAndData
from bigcrittercolor.downloadImagesUsingDarwinCore import downloadImagesUsingDarwinCore
from bigcrittercolor.inferMasks import inferMasks
from bigcrittercolor.filterExtractSegs import filterExtractSegs
from bigcrittercolor.clusterColorsToPatterns import clusterColorsToPatterns
from bigcrittercolor.writeColorMetrics import writeColorMetrics