site_name: bigcrittercolor Docs

theme:
  name: "material"
  logo: 'temp_logo.png'

plugins:
  - mkdocstrings

nav:
  - index.md
  - 1. Project Prep: 1projprep.md
  - 2. Image download: 2imgdownload.md
  - 3. Segmentation: 3segmentation.md
  - 4. Filtering: 4filterextract.md
  - 5. Trait extraction: 5traits.md